# Generated by Django 5.1 on 2024-08-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_user_arn_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField()),
                ('response', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
    ]
